/**
 * Seed data for Clarifications prototype. Edit freely for new test cases.
 */
import type { Clarification, FocusItem } from './types'

/** Demo supplier portal user — Tom @ EvoEnergy */
export const DEMO_SUPPLIER_ID = 'evo-energy'
export const DEMO_SUPPLIER_NAME = 'Evo Energy'

export const DEFAULT_BID_CONTEXT_322: Record<string, string> = {
  'Total CapEx': '£412k',
  'PPA rate': '9.4 p/kWh',
  Maintenance: '£12.3k / yr',
  Warranty: '20 years performance',
}

/**
 * Recipient checklist for Raise modal — IDs align with `/supplier-comparison` rows (Solar, LED, Rostock).
 */
export const MOCK_CLARIFICATION_RECIPIENTS = [
  { id: 'electron-green', name: 'Electron Green' },
  { id: 'sustain-commercial-solar', name: 'Sustain Commercial Solar' },
  { id: 'low-carbon-energy-company', name: 'The Low Carbon Energy Company Ltd' },
  { id: 'ortus-energy-ltd', name: 'Ortus Energy Ltd.' },
  { id: 'evo-energy', name: 'Evo Energy' },
  { id: 'oracle-energy', name: 'Oracle Energy' },
  { id: 'german-led-tech', name: 'German LED Tech' },
  { id: 'ecowatt', name: 'Ecowatt GmbH' },
  { id: 'die-stromspar', name: 'Die Stromspar GmbH' },
  { id: 'led-on', name: 'LED ON GmbH' },
  { id: 'beka-solar', name: 'Beka Solar Energie GmbH' },
  { id: 'genesis', name: 'Genesis 1.3 Limited' },
  { id: 'saflux', name: 'SAFLUX GmbH' },
  { id: 'die-stromspar-rostock', name: 'Die Stromspar GmbH' },
  { id: 'wisag-rostock', name: 'WISAG Gebäudetechnik Nord-Ost' },
] satisfies Array<{ id: string; name: string }>

/** Supplier-comparison / tender 322 — Braehead shopping centre */
export const DEFAULT_CLARIFICATION_PROJECT = 'Project 322 — Braehead'

/** Match comparison route context when opening Raise modal */
export type ClarificationsProjectSlug = 'solar' | 'led' | 'led-rostock'

export function clarificationProjectLabel(
  slug: ClarificationsProjectSlug,
): string {
  if (slug === 'led') return 'Alexanderstraße Berlin LED'
  if (slug === 'led-rostock') return 'Doberaner Straße Rostock LED'
  return DEFAULT_CLARIFICATION_PROJECT
}

export function clarificationBidId(slug: ClarificationsProjectSlug): string {
  if (slug === 'led') return '310'
  if (slug === 'led-rostock') return '651'
  return '322'
}

/** Clarifications raised in the context of a supplier-comparison / tender route. */
export function clarificationsForTenderSlug(
  items: Clarification[],
  slug: ClarificationsProjectSlug,
): Clarification[] {
  const project = clarificationProjectLabel(slug)
  const bidId = clarificationBidId(slug)
  return items.filter((c) => c.project === project && c.bidId === bidId)
}

/** Shared by the eight seeded “same question, many suppliers” rows */
export const SEED_PPA_RATE_MULTI_DISPATCH_ID = 'disp-001'
export const SEED_FINANCING_MULTI_DISPATCH_ID = 'disp-002'
export const SEED_OM_SCOPE_MULTI_DISPATCH_ID = 'disp-003'
export const SEED_ACCESS_LIFTING_MULTI_DISPATCH_ID = 'disp-004'
export const SEED_WARRANTY_MULTI_DISPATCH_ID = 'disp-005'
export const SEED_EXPORT_G99_MULTI_DISPATCH_ID = 'disp-006'
export const SEED_COMMISSIONING_MULTI_DISPATCH_ID = 'disp-007'

const PPA_RATE_MULTI_TITLE = 'PPA rate clarification'
const PPA_RATE_MULTI_QUESTION =
  'Can you confirm the PPA escalation path after year one and confirm whether indexation caps out in year 15?'

const FINANCING_MULTI_TITLE =
  'Do you offer any other financing options besides CapEx and PPA?'
const FINANCING_MULTI_QUESTION = FINANCING_MULTI_TITLE

const OM_SCOPE_MULTI_TITLE = 'O&M scope clarification'
const OM_SCOPE_MULTI_QUESTION =
  'Please clarify whether inverter replacement labour is covered under the headline O&M line or priced separately.'

const ACCESS_LIFTING_MULTI_TITLE = 'Access & lifting package'
const ACCESS_LIFTING_MULTI_QUESTION =
  'We need crane mobilisation assumptions and weekday vs weekend outage windows for LL3 rooftop.'

const WARRANTY_MULTI_TITLE = 'Warranty term alignment'
const WARRANTY_MULTI_QUESTION =
  'Please align performance warranty term with module manufacturer deck (25 years) instead of 20 years shown in schedule.'

const EXPORT_G99_MULTI_TITLE = 'Deemed export capacity'
const EXPORT_G99_MULTI_QUESTION =
  'Confirm whether each bid includes G99 queue position and export MPAN registration as part of handover documentation.'

const COMMISSIONING_MULTI_TITLE = 'Commissioning evidence pack'
const COMMISSIONING_MULTI_QUESTION =
  'Confirm format of handover commissioning pack (IV curve traces, witness test sign-off, DNO G99 letter).'

export const SEED_CLARIFICATIONS: Clarification[] = [
  {
    id: 'cl-disp001-1',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 1',
    supplier: 'Evo Energy',
    supplierId: 'evo-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'review',
    reply: {
      text: 'Confirming escalation is +2.5% annually, capped until year 15. After year 15 the rate fixes at year-15 nominal value.',
      from: 'Tom',
      fromCompany: 'Evo Energy',
      timeAgo: '4 hours ago',
      source: 'on-platform reply',
      trust: 'high',
      attachments: [
        { name: 'PPA-appendix-draft.pdf', sizeLabel: '1.5 MB' },
        { name: 'Rate-sheet.xlsx', sizeLabel: '480 KB' },
      ],
    },
    impact: {
      fieldLabel: 'PPA rate',
      currentValue: '9.4 p/kWh',
      currentNote: '(interpretation unclear)',
      proposedValue: '9.4 p/kWh year 1',
      proposedNote: '+2.5% p.a., capped year 15',
    },
  },
  {
    id: 'cl-disp001-2',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 2',
    supplier: 'Oracle Energy',
    supplierId: 'oracle-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'review',
    reply: {
      text: 'We model +2.5% p.a. with a hard cap at year 15 nominal; happy to align schedule wording to match.',
      from: 'Sam',
      fromCompany: 'Oracle Energy',
      timeAgo: '6h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'PPA rate',
      currentValue: '9.2 p/kWh',
      currentNote: '(schedule silent post year 15)',
      proposedValue: '9.2 p/kWh year 1',
      proposedNote: '+2.5% p.a., cap year 15',
    },
  },
  {
    id: 'cl-disp001-3',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 3',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-disp001-4',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 4',
    supplier: 'Sustain Commercial Solar',
    supplierId: 'sustain-commercial-solar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  {
    id: 'cl-disp001-5',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 5',
    supplier: 'The Low Carbon Energy Company Ltd',
    supplierId: 'low-carbon-energy-company',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'need_response',
    reply: {
      text: 'Our finance model caps at year 12, not 15 — can ops confirm which interpretation the client signed off?',
      from: 'Chris',
      fromCompany: 'The Low Carbon Energy Company Ltd',
      timeAgo: '1d ago',
      source: 'on-platform reply',
      trust: 'medium',
    },
  },
  {
    id: 'cl-disp001-6',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 6',
    supplier: 'German LED Tech',
    supplierId: 'german-led-tech',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  {
    id: 'cl-disp001-7',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 7',
    supplier: 'Ortus Energy Ltd.',
    supplierId: 'ortus-energy-ltd',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'applied',
    reply: {
      text: 'Confirmed: indexation +2.5% to year 15 then fixed — already reflected in our financial model v3.',
      from: 'Alex',
      fromCompany: 'Ortus Energy Ltd.',
      timeAgo: '3d ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'PPA rate',
      currentValue: '9.5 p/kWh',
      proposedValue: '9.5 p/kWh · +2.5% to yr 15',
      proposedNote: 'Accepted schedule',
    },
  },
  {
    id: 'cl-disp001-8',
    dispatchId: SEED_PPA_RATE_MULTI_DISPATCH_ID,
    title: PPA_RATE_MULTI_TITLE,
    question: PPA_RATE_MULTI_QUESTION,
    linkedField: 'PPA rate',
    bidId: '322',
    bidLabel: 'Bid 8',
    supplier: 'Ecowatt GmbH',
    supplierId: 'ecowatt',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'closed',
    reply: {
      text: 'We cannot meet the year-15 cap language under our current bank covenant; withdrawing this line item from consideration.',
      from: 'Ingrid',
      fromCompany: 'Ecowatt GmbH',
      timeAgo: '2d ago',
      source: 'manual',
      trust: 'low',
    },
  },
  // disp-002 — financing options (2 suppliers)
  {
    id: 'cl-disp002-1',
    dispatchId: SEED_FINANCING_MULTI_DISPATCH_ID,
    title: FINANCING_MULTI_TITLE,
    question: FINANCING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 1',
    supplier: 'Genesis 1.3 Limited',
    supplierId: 'genesis',
    project: 'Solar PV - Walter Scott House',
    raisedAgo: '5h ago',
    raisedBy: 'Lucija',
    status: 'review',
    reply: {
      text: 'We can offer a lease-purchase structure alongside CapEx and PPA — term sheet attached for ops review.',
      from: 'Mark',
      fromCompany: 'Genesis 1.3 Limited',
      timeAgo: '5h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'Financing',
      currentValue: 'CapEx / PPA only',
      proposedValue: 'Lease-purchase option added',
    },
  },
  {
    id: 'cl-disp002-2',
    dispatchId: SEED_FINANCING_MULTI_DISPATCH_ID,
    title: FINANCING_MULTI_TITLE,
    question: FINANCING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 2',
    supplier: 'Beka Solar Energie GmbH',
    supplierId: 'beka-solar',
    project: 'Solar PV - Walter Scott House',
    raisedAgo: '5h ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  // disp-003 — O&M scope (5 suppliers)
  {
    id: 'cl-disp003-1',
    dispatchId: SEED_OM_SCOPE_MULTI_DISPATCH_ID,
    title: OM_SCOPE_MULTI_TITLE,
    question: OM_SCOPE_MULTI_QUESTION,
    linkedField: 'Maintenance',
    bidId: '322',
    bidLabel: 'Bid 1',
    supplier: 'Oracle Energy',
    supplierId: 'oracle-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '5d ago',
    raisedBy: 'Jamie',
    status: 'review',
    overdue: true,
    reply: {
      text: 'Inverter replacement labour included in headline O&M; parts beyond warranty priced as variations.',
      from: 'Sam',
      fromCompany: 'Oracle Energy',
      timeAgo: '1d ago',
      source: 'doc-extract',
      trust: 'medium',
    },
    impact: {
      fieldLabel: 'O&M (annual)',
      currentValue: '£12.3k',
      proposedValue: '£12.3k · labour inclusive',
      proposedNote: 'Inverter swaps under SLA',
    },
  },
  {
    id: 'cl-disp003-2',
    dispatchId: SEED_OM_SCOPE_MULTI_DISPATCH_ID,
    title: OM_SCOPE_MULTI_TITLE,
    question: OM_SCOPE_MULTI_QUESTION,
    linkedField: 'Maintenance',
    bidId: '322',
    bidLabel: 'Bid 2',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '5d ago',
    raisedBy: 'Jamie',
    status: 'review',
    reply: {
      text: 'Labour for inverter swap included; we price DC isolator upgrades as day-rate variations only.',
      from: 'Riya',
      fromCompany: 'Electron Green',
      timeAgo: '8h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'O&M (annual)',
      currentValue: '£11.8k',
      proposedValue: '£11.8k · swaps in scope',
    },
  },
  {
    id: 'cl-disp003-3',
    dispatchId: SEED_OM_SCOPE_MULTI_DISPATCH_ID,
    title: OM_SCOPE_MULTI_TITLE,
    question: OM_SCOPE_MULTI_QUESTION,
    linkedField: 'Maintenance',
    bidId: '322',
    bidLabel: 'Bid 3',
    supplier: 'Sustain Commercial Solar',
    supplierId: 'sustain-commercial-solar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '5d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-disp003-4',
    dispatchId: SEED_OM_SCOPE_MULTI_DISPATCH_ID,
    title: OM_SCOPE_MULTI_TITLE,
    question: OM_SCOPE_MULTI_QUESTION,
    linkedField: 'Maintenance',
    bidId: '322',
    bidLabel: 'Bid 4',
    supplier: 'SAFLUX GmbH',
    supplierId: 'saflux',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '5d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  {
    id: 'cl-disp003-5',
    dispatchId: SEED_OM_SCOPE_MULTI_DISPATCH_ID,
    title: OM_SCOPE_MULTI_TITLE,
    question: OM_SCOPE_MULTI_QUESTION,
    linkedField: 'Maintenance',
    bidId: '322',
    bidLabel: 'Bid 5',
    supplier: 'Die Stromspar GmbH',
    supplierId: 'die-stromspar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '5d ago',
    raisedBy: 'Jamie',
    status: 'applied',
    reply: {
      text: 'All inverter labour within fixed O&M — no separate provisional required.',
      from: 'Klaus',
      fromCompany: 'Die Stromspar GmbH',
      timeAgo: '4d ago',
      source: 'on-platform reply',
      trust: 'verified',
    },
  },
  // disp-004 — access & lifting (4 suppliers)
  {
    id: 'cl-disp004-1',
    dispatchId: SEED_ACCESS_LIFTING_MULTI_DISPATCH_ID,
    title: ACCESS_LIFTING_MULTI_TITLE,
    question: ACCESS_LIFTING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 1',
    supplier: 'Sustain Commercial Solar',
    supplierId: 'sustain-commercial-solar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '1w ago',
    raisedBy: 'Lucija',
    status: 'need_response',
    reply: {
      text: 'We do not currently hold the landlord lifting protocol for LL3. Can you share the approved method statement when available?',
      from: 'Priya',
      fromCompany: 'Sustain Commercial Solar',
      timeAgo: '3d ago',
      source: 'on-platform reply',
      trust: 'verified',
    },
  },
  {
    id: 'cl-disp004-2',
    dispatchId: SEED_ACCESS_LIFTING_MULTI_DISPATCH_ID,
    title: ACCESS_LIFTING_MULTI_TITLE,
    question: ACCESS_LIFTING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 2',
    supplier: 'WISAG Gebäudetechnik Nord-Ost',
    supplierId: 'wisag-rostock',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '1w ago',
    raisedBy: 'Lucija',
    status: 'review',
    reply: {
      text: 'Crane booked for weekend slot only; weekday outage limited to 6 hours — see attached lift plan.',
      from: 'Stefan',
      fromCompany: 'WISAG Gebäudetechnik Nord-Ost',
      timeAgo: '12h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
  },
  {
    id: 'cl-disp004-3',
    dispatchId: SEED_ACCESS_LIFTING_MULTI_DISPATCH_ID,
    title: ACCESS_LIFTING_MULTI_TITLE,
    question: ACCESS_LIFTING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 3',
    supplier: 'LED ON GmbH',
    supplierId: 'led-on',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '1w ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  {
    id: 'cl-disp004-4',
    dispatchId: SEED_ACCESS_LIFTING_MULTI_DISPATCH_ID,
    title: ACCESS_LIFTING_MULTI_TITLE,
    question: ACCESS_LIFTING_MULTI_QUESTION,
    bidId: '322',
    bidLabel: 'Bid 4',
    supplier: 'German LED Tech',
    supplierId: 'german-led-tech',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '1w ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
    overdue: true,
  },
  // disp-005 — warranty (6 suppliers, mostly awaiting)
  {
    id: 'cl-disp005-1',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 1',
    supplier: 'The Low Carbon Energy Company Ltd',
    supplierId: 'low-carbon-energy-company',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  {
    id: 'cl-disp005-2',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 2',
    supplier: 'Evo Energy',
    supplierId: 'evo-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'review',
    reply: {
      text: 'We will align schedule to 25-year performance warranty to match JA Solar module deck.',
      from: 'Tom',
      fromCompany: 'Evo Energy',
      timeAgo: '6h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'Warranty',
      currentValue: '20 years',
      proposedValue: '25 years performance',
    },
  },
  {
    id: 'cl-disp005-3',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 3',
    supplier: 'Ortus Energy Ltd.',
    supplierId: 'ortus-energy-ltd',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  {
    id: 'cl-disp005-4',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 4',
    supplier: 'Ecowatt GmbH',
    supplierId: 'ecowatt',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  {
    id: 'cl-disp005-5',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 5',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-disp005-6',
    dispatchId: SEED_WARRANTY_MULTI_DISPATCH_ID,
    title: WARRANTY_MULTI_TITLE,
    question: WARRANTY_MULTI_QUESTION,
    linkedField: 'Warranty',
    bidId: '322',
    bidLabel: 'Bid 6',
    supplier: 'Genesis 1.3 Limited',
    supplierId: 'genesis',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  // disp-006 — G99 / export (6 suppliers)
  {
    id: 'cl-disp006-1',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 1',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'review',
    reply: {
      text: 'G99 application reference included; export MPAN registration at energisation per our standard handover pack.',
      from: 'Riya',
      fromCompany: 'Electron Green',
      timeAgo: '2h ago',
      source: 'on-platform reply',
      trust: 'high',
    },
  },
  {
    id: 'cl-disp006-2',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 2',
    supplier: 'Oracle Energy',
    supplierId: 'oracle-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'review',
    reply: {
      text: 'Queue position held; MPAN paperwork issued on practical completion — draft attached.',
      from: 'Sam',
      fromCompany: 'Oracle Energy',
      timeAgo: '5h ago',
      source: 'doc-extract',
      trust: 'medium',
    },
  },
  {
    id: 'cl-disp006-3',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 3',
    supplier: 'Sustain Commercial Solar',
    supplierId: 'sustain-commercial-solar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'awaiting',
  },
  {
    id: 'cl-disp006-4',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 4',
    supplier: 'Evo Energy',
    supplierId: 'evo-energy',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'awaiting',
  },
  {
    id: 'cl-disp006-5',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 5',
    supplier: 'Beka Solar Energie GmbH',
    supplierId: 'beka-solar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-disp006-6',
    dispatchId: SEED_EXPORT_G99_MULTI_DISPATCH_ID,
    title: EXPORT_G99_MULTI_TITLE,
    question: EXPORT_G99_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 6',
    supplier: 'SAFLUX GmbH',
    supplierId: 'saflux',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '4d ago',
    raisedBy: 'Ops',
    status: 'applied',
    reply: {
      text: 'G99 and MPAN confirmed in appendix C — no further action required from client.',
      from: 'Lena',
      fromCompany: 'SAFLUX GmbH',
      timeAgo: '1d ago',
      source: 'on-platform reply',
      trust: 'verified',
    },
  },
  // disp-007 — commissioning pack (4 suppliers, mixed progress)
  {
    id: 'cl-disp007-1',
    dispatchId: SEED_COMMISSIONING_MULTI_DISPATCH_ID,
    title: COMMISSIONING_MULTI_TITLE,
    question: COMMISSIONING_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 1',
    supplier: 'Ortus Energy Ltd.',
    supplierId: 'ortus-energy-ltd',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Ops',
    status: 'review',
    reply: {
      text: 'IV curves and witness sign-off included; DNO G99 letter issued within 10 working days of PC.',
      from: 'Alex',
      fromCompany: 'Ortus Energy Ltd.',
      timeAgo: '1d ago',
      source: 'on-platform reply',
      trust: 'high',
    },
  },
  {
    id: 'cl-disp007-2',
    dispatchId: SEED_COMMISSIONING_MULTI_DISPATCH_ID,
    title: COMMISSIONING_MULTI_TITLE,
    question: COMMISSIONING_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 2',
    supplier: 'Die Stromspar GmbH',
    supplierId: 'die-stromspar',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Ops',
    status: 'awaiting',
  },
  {
    id: 'cl-disp007-3',
    dispatchId: SEED_COMMISSIONING_MULTI_DISPATCH_ID,
    title: COMMISSIONING_MULTI_TITLE,
    question: COMMISSIONING_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 3',
    supplier: 'LED ON GmbH',
    supplierId: 'led-on',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Ops',
    status: 'awaiting',
  },
  {
    id: 'cl-disp007-4',
    dispatchId: SEED_COMMISSIONING_MULTI_DISPATCH_ID,
    title: COMMISSIONING_MULTI_TITLE,
    question: COMMISSIONING_MULTI_QUESTION,
    bidId: '415',
    bidLabel: 'Bid 4',
    supplier: 'German LED Tech',
    supplierId: 'german-led-tech',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2d ago',
    raisedBy: 'Ops',
    status: 'review',
    reply: {
      text: 'Commissioning pack follows VDE-AR-N 4105 template; IV traces uploaded to shared data room.',
      from: 'Hans',
      fromCompany: 'German LED Tech',
      timeAgo: '3d ago',
      source: 'on-platform reply',
      trust: 'medium',
    },
  },
  {
    id: 'cl-evo-export-limit',
    dispatchId: 'disp-cl-evo-export-limit',
    title: 'Export capacity clarification',
    question:
      'Confirm whether the 100 kW export assumption in our bid remains valid if the client upgrades the main incomer in Q3.',
    linkedField: 'Export capacity',
    bidContext: {
      ...DEFAULT_BID_CONTEXT_322,
      'Export capacity': '100 kW capped',
    },
    bidSubmittedLabel: 'Submitted 14 days ago',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: DEMO_SUPPLIER_NAME,
    supplierId: DEMO_SUPPLIER_ID,
    project: 'Solar PV - Schenkendorfstraße',
    raisedAgo: '5h ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-evo-ppa-path',
    dispatchId: 'disp-cl-evo-ppa-path',
    title: 'PPA rate clarification',
    question:
      'Can you confirm the PPA escalation path after year one and whether indexation caps out in year 15?',
    linkedField: 'PPA rate',
    bidContext: DEFAULT_BID_CONTEXT_322,
    bidSubmittedLabel: 'Submitted 14 days ago',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: DEMO_SUPPLIER_NAME,
    supplierId: DEMO_SUPPLIER_ID,
    project: 'Solar PV - Schenkendorfstraße',
    raisedAgo: '2d ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  {
    id: 'cl-evo-om-split',
    dispatchId: 'disp-cl-evo-om-split',
    title: 'O&M scope — inverter labour',
    question:
      'Please confirm inverter replacement labour sits inside the headline O&M fee rather than as a provisional.',
    linkedField: 'Maintenance',
    bidContext: DEFAULT_BID_CONTEXT_322,
    bidSubmittedLabel: 'Submitted 14 days ago',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: DEMO_SUPPLIER_NAME,
    supplierId: DEMO_SUPPLIER_ID,
    project: 'Solar PV - Schenkendorfstraße',
    raisedAgo: '4d ago',
    raisedBy: 'Jamie',
    status: 'awaiting',
  },
  {
    id: 'cl-evo-access-crane',
    dispatchId: 'disp-cl-evo-access-crane',
    title: 'Crane mobilisation windows',
    question:
      'Share crane mobilisation assumptions and confirm weekday-only outage windows for the LL3 rooftop phase.',
    linkedField: 'Total CapEx',
    bidContext: DEFAULT_BID_CONTEXT_322,
    bidSubmittedLabel: 'Submitted 14 days ago',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: DEMO_SUPPLIER_NAME,
    supplierId: DEMO_SUPPLIER_ID,
    project: 'Solar PV - Schenkendorfstraße',
    raisedAgo: '1w ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
  },
  {
    id: 'cl-hs-await-od',
    dispatchId: 'disp-cl-hs-await-od',
    title: 'H&S provisional split',
    question:
      'Break out edge protection vs crane hire within the H&S provisional so we can benchmark against other bids.',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '6d ago',
    raisedBy: 'Lucija',
    status: 'awaiting',
    overdue: true,
  },
  {
    id: 'cl-applied-panel',
    dispatchId: 'disp-cl-applied-panel',
    title: 'Panel manufacturer lock-in',
    question: 'Confirm whether alternate Tier-1 module brands remain acceptable post shortlist.',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: 'Ortus Energy Ltd.',
    supplierId: 'ortus-energy-ltd',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '2w ago',
    raisedBy: 'Lucija',
    status: 'applied',
    reply: {
      text: 'We will lock JA Solar for this phase; alternates withdrawn subject to LC approval.',
      from: 'Alex',
      fromCompany: 'Ortus Energy Ltd.',
      timeAgo: '13d ago',
      source: 'on-platform reply',
      trust: 'high',
    },
    impact: {
      fieldLabel: 'Module OEM',
      currentValue: 'Tier-1 alternate allowed',
      proposedValue: 'JA Solar nominated',
      proposedNote: 'Alternates withdrawn',
    },
  },
  {
    id: 'cl-closed-dno',
    dispatchId: 'disp-cl-closed-dno',
    title: 'Feed-in limit assumption',
    question: 'Clarify whether 100 kW export cap is feeder-level or MPAN-level for Red Car Park roofs.',
    bidId: '322',
    bidLabel: 'Bid 322',
    supplier: 'Electron Green',
    supplierId: 'electron-green',
    project: DEFAULT_CLARIFICATION_PROJECT,
    raisedAgo: '3w ago',
    raisedBy: 'Jamie',
    status: 'closed',
    reply: {
      text: 'We interpreted as MPAN-level; awaiting DNO clarification from client team — parking this thread.',
      from: 'Riya',
      fromCompany: 'Electron Green',
      timeAgo: '19d ago',
      source: 'manual',
      trust: 'low',
    },
  },
]

/** Bid update + profile placeholders; question cards are derived from clarifications in the shared store. */
export const SEED_FOCUS_NON_QUESTION_ITEMS: FocusItem[] = [
  {
    id: 'fi-bid-update',
    kind: 'bid_update',
    title: 'Revised line items uploaded',
    contextLine: 'Leeds warehouse · Atlas Retail',
    ageLabel: '1d',
    primaryAction: 'go_to_project',
  },
  {
    id: 'fi-profile',
    kind: 'profile',
    title: 'Insurance certificate expiring',
    contextLine: `Company profile · ${DEMO_SUPPLIER_NAME}`,
    ageLabel: '3d',
    primaryAction: 'go_to_profile',
  },
]
